#!/usr/bin/env bash
# Cursor Agent launcher — opens `agent` in the agent's folder, governed by Agentric.
#
# HOW THE INVARIANT IS UPHELD:
#   1. Project hooks at `$AGENT_DIR/.cursor/hooks.json` call terminal/cursor-gate-hook.sh for
#      beforeShellExecution, beforeMCPExecution, and preToolUse (writes). failClosed:true so a
#      hook crash never fails open.
#   2. Connectors from Agentric are written to `$AGENT_DIR/.cursor/mcp.json` (Cursor's MCP schema).
#   3. Company context + CLAUDE.md are folded into AGENTS.md (Cursor discovers that).
#   4. Unattended: `agent -p --trust --approve-mcps` (print mode; exits at turn end).
#      Interactive: `agent --trust --approve-mcps` with the task as the opening prompt.
#      We do NOT pass --force/--yolo — Agentric's hooks are the authority; Cursor's own auto-approve
#      would race them.
#
# Env: AOS_URL, SESSION, AGENT, AGENT_DIR, TASK_FILE, HOOK, MCP_CONFIG, COMPANY_FILE,
#      CURSOR_MODEL, UNATTENDED, RESUME, RUNTIME_SESSION_ID, AOS_SECRET, AOS_TENANT
set -u

if [ "${RESUME:-}" = "1" ] && [ -n "${ENV_FILE:-}" ] && [ -f "${ENV_FILE}" ]; then
  # shellcheck disable=SC1090
  . "$ENV_FILE"
fi

export PATH="$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"

if [ -n "${TASK_FILE:-}" ] && [ -f "${TASK_FILE}" ]; then
  TASK=$(cat "${TASK_FILE}")
else
  TASK=$(printf '%s' "${TASK_B64:-}" | base64 -d 2>/dev/null)
fi

cyan() { printf '\033[36m%s\033[0m\n' "$1"; }
dim()  { printf '\033[2m%s\033[0m\n' "$1"; }
red()  { printf '\033[31m%s\033[0m\n' "$1"; }

cd "$AGENT_DIR" 2>/dev/null || { red "agent folder not found: $AGENT_DIR"; exec bash; }

notify_ended_early() {
  curl -s -X POST "$AOS_URL/api/ended" -H 'content-type: application/json' \
    -H "x-aos-secret: ${AOS_SECRET:-}" -H "x-aos-tenant: ${AOS_TENANT:-}" \
    -d "$(node -e 'console.log(JSON.stringify({session:process.argv[1]}))' "$SESSION")" >/dev/null 2>&1 || true
}

park() {
  notify_ended_early
  [ "${UNATTENDED:-}" = "1" ] && exit 1
  while true; do
    dim "Press [q] to close this tab."
    key=""
    IFS= read -rsn1 key || { sleep 5; continue; }
    case "$key" in q|Q) exit 1 ;; *) : ;; esac
  done
}

if ! command -v agent >/dev/null 2>&1; then
  red "the Cursor 'agent' CLI is not on PATH — install from https://cursor.com/docs/cli"
  echo
  cyan "    curl https://cursor.com/install -fsS | bash"
  echo
  park
fi

# Auth: logged-in session (agent login) or CURSOR_API_KEY.
if [ -z "${CURSOR_API_KEY:-}" ]; then
  if ! agent status >/dev/null 2>&1; then
    red "Cursor Agent is not authenticated — refusing to start."
    echo
    dim "Fix once from a normal shell:"
    echo
    cyan "    agent login"
    echo
    dim "Or set CURSOR_API_KEY on this agent / in Secrets."
    echo
    park
  fi
fi

# ── gate hook + hooks.json ────────────────────────────────────────────────────────
HOOK_DIR="$AGENT_DIR/.cursor/hooks"
mkdir -p "$HOOK_DIR" || { red "cannot create $HOOK_DIR — refusing to start ungoverned."; park; }
if ! cp "$HOOK" "$HOOK_DIR/aos-gate.sh"; then
  red "failed to install the Agentric Cursor gate hook — refusing to start ungoverned."
  park
fi
chmod +x "$HOOK_DIR/aos-gate.sh"

# Absolute path in hooks.json so Cursor resolves it regardless of cwd quirks.
GATE_ABS="$HOOK_DIR/aos-gate.sh"
cat > "$AGENT_DIR/.cursor/hooks.json" <<EOF
{
  "version": 1,
  "hooks": {
    "beforeShellExecution": [
      { "command": "$GATE_ABS", "failClosed": true }
    ],
    "beforeMCPExecution": [
      { "command": "$GATE_ABS", "failClosed": true }
    ],
    "preToolUse": [
      { "command": "$GATE_ABS", "failClosed": true, "matcher": "Write|Delete|Edit|Shell|MCP:.*" }
    ]
  }
}
EOF

# ── mcp.json (connectors) ─────────────────────────────────────────────────────────
# Cursor uses the same mcpServers shape as other agent CLIs for stdio/http.
if [ -n "${MCP_CONFIG:-}" ] && [ -f "${MCP_CONFIG}" ]; then
  cp "$MCP_CONFIG" "$AGENT_DIR/.cursor/mcp.json" || {
    red "failed to materialise .cursor/mcp.json"
    park
  }
  chmod 600 "$AGENT_DIR/.cursor/mcp.json" 2>/dev/null || true
fi

# ── AGENTS.md (persona + company) ─────────────────────────────────────────────────
node -e '
  const fs = require("fs");
  const [persona, company, dest] = process.argv.slice(1);
  const read = (p) => { try { return p && fs.existsSync(p) ? fs.readFileSync(p, "utf8").trim() : ""; } catch (_) { return ""; } };
  const parts = ["<!-- Generated by Agentric at launch. Edits are overwritten; change the agent or Company context instead. -->"];
  const p = read(persona), c = read(company);
  if (p) parts.push(p);
  if (c) parts.push(c);
  if (p || c) fs.writeFileSync(dest, parts.join("\n\n") + "\n");
' "$AGENT_DIR/CLAUDE.md" "${COMPANY_FILE:-}" "$AGENT_DIR/AGENTS.md" 2>/dev/null || true

# ── launch ────────────────────────────────────────────────────────────────────────
ARGS=(--trust --approve-mcps --workspace "$AGENT_DIR")
[ -n "${CURSOR_MODEL:-}" ] && ARGS+=(--model "$CURSOR_MODEL")

if [ "${RESUME:-}" = "1" ] && [ -n "${RUNTIME_SESSION_ID:-}" ]; then
  ARGS+=(--resume "$RUNTIME_SESSION_ID")
fi

trap notify_ended_early EXIT

if [ "${UNATTENDED:-}" = "1" ]; then
  # Print mode: one-shot, exits when the turn finishes. Do NOT add --force — that bypasses Cursor
  # prompts AND would race our hooks; the hooks + failClosed are the fail-closed path.
  exec agent -p --output-format text "${ARGS[@]+"${ARGS[@]}"}" "$TASK"
fi

# Interactive TUI: opening task as the first prompt.
exec agent "${ARGS[@]+"${ARGS[@]}"}" "$TASK"
